---
  version: '3'
  volumes:
    project-slug-database:
  services:
    database:
      image: mariadb:10
      ports:
        - 3306:3306
      volumes:
        - project-slug-database:/var/lib/mysql
      environment:
        MYSQL_DATABASE: database
        MYSQL_USER: username
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root
    # cache:
    #   image: redis:5-alpine
    #   ports:
    #     - 6379:6379
    app:
      user: www-data:1000
      build: .
      command: php artisan serve --host=0.0.0.0 --port=8000
      working_dir: /app
      volumes:
        - .:/app
      depends_on:
        # - cache
        - database
      ports:
        - 8000:8000
      environment:
        APP_DEBUG: 'true'
    # job:
    #   build: .
    #   command: php artisan queue:listen --tries=3
    #   working_dir: /app
    #   volumes:
    #     - .:/app
    #   depends_on:
    #     - database
